### PR TITLE
Update potionization.py

### PR DESCRIPTION
**Pull request by rshelly8**

### CODE REVIEW

**Comment by Braeizzle1** [comment]
PLEASE STOP, YOU’RE BLOWING UP MY EMAIL

**Comment by johnlmcc** [comment]
Excuse me I am not in EECS 183 anymore, Could you please remove me from
this thread?

**Comment by rnbrewer** [comment]
please remove me from these threads I am no longer in 183

**Comment by jmofclou** [comment]
Please remove me too!

**Comment by ajmorg** [comment]
RT

**Comment by jproeser** [comment]
Please remove me as well.

James Roeser
University of Michigan Class of 2018
School of Literature Science and Arts
jproeser@umich.edu
www.linkedin.com/in/jamesroeser

**Comment by emcartwright** [comment]
I would also appreciate being removed from these threads. I’m not in 183 anymore.
Thanks.

**Comment by Braeizzle1** [comment]
remove me please, this is so annoying

**Comment by zach-fattal** [comment]
Can you please remove me from this thread?

Cheers,
Zach Fattal

**Comment by dadler701** [comment]
Remove me too. How did this happen?

**Comment by rowandaiksel** [comment]
Me too

**Comment by skyeliam** [comment]
JUST UNSUBSCRIBE. THERE IS A VERY OBVIOUS BUTTON ON THE SIDE OF THE PAGE.
image

**Comment by rhenney** [comment]
Please remove me too. I was In this last semester.

**Comment by mattjw9** [comment]
Either stop replying or remove me from this

**Comment by anans14** [comment]
Please remove me as well i was in eecs last semester

**Comment by shyamshah** [comment]
Please remove me from this thread.

**Comment by esthertrager** [comment]
No one can remove you.  You have to sign into git and unwatch the repository.

**Comment by rdkibler** [comment]
nobody cares

**Comment by skyeliam** [comment]
UNSUBSCRIBE FROM THE THREAD THERE IS A BUTTON ON THE SIDE OF THE PAGE.

**Comment by emiljanelezi** [comment]
Please remove as well. I’m not in the class anymore.

Emiljan Elezi
University of Michigan Evans Scholar ‘19
586.668.7082
elezi@umich.edu

**Comment by skyeliam** [comment]
IT IS VERY OBVIOUS

**Comment by surajshekar97** [comment]
Please remove me as well.

**Comment by skyeliam** [comment]
YOU CANNOT BE REMOVED

**Comment by skyeliam** [comment]
image
THERE IS A BUTTON THAT LOOKS LIKE THIS ON THE SIDE OF THE PAGE

**Comment by emiljanelezi** [comment]
OKAY.

Emiljan Elezi
University of Michigan Evans Scholar ‘19
586.668.7082
elezi@umich.edu

**Comment by afelix96** [comment]
anyone wanna hang out?

**Comment by skyeliam** [comment]
Also if you comment again it automatically resubscribes you. Keep that in mind.

**Comment by rnbrewer** [comment]
I'm about to change my uniqname

**Comment by skyeliam** [comment]
Well you could just press the unsubscribe button, that would be a tad easier wouldn't it?

**Pull request closed without merging**
